### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by CyBork2000** [Debitosphere/CNC.TA.Crucial.Scripts#1]
Hi Debitosphere,

after the last update i can not use your script anymore.
The game is not playable anymore with it.
i can not click on attack. the attack button does not work anymore.
![image](https://cloud.githubusercontent.com/assets/24613601/21278659/bf264bc8-c3dc-11e6-9cff-0aae6d8b340c.png)

if i double click on the outpost i will get into it, but still can not attack.
![image](https://cloud.githubusercontent.com/assets/24613601/21278637/aa8390ae-c3dc-11e6-9cc0-64d3d898da9f.png)

the unit repair button in the right corner is there but also not click able.
![image](https://cloud.githubusercontent.com/assets/24613601/21278615/9442d250-c3dc-11e6-8f03-a38a7b8dab31.png)

i tried different things. 
updated chrom to the last version. 
deleted the profile from chrom. 
installed all new. (Tampermonkey and CNC.TA.Crucial.Script ) 
but the issue still exist.

**Comment by Debitosphere** [comment]
The only thing i can think of is two of the same script running....
please re-check if an extension is running that may have a conflicting script or collection active.

**Comment by CyBork2000** [comment]
No other script was installed.
thats why i m writing you and try to solve this issue.
i used the previous version, and had many open cnc windows during the last night and a few crashed.
Dont know why. and after the reload i ve seen that you have an update so i updated the script.
during other windows where still active with the older version. maybe that could cause a problem.
befor i reseted all i had used a few more skripts. like baseinfo,memberstats and the wavy script.
but as i ve written in the entry message, i deleted all scripts and updated chrom. installed your skript stand alone and the issue was still there.

**Comment by Debitosphere** [comment]
I tried replicating your issues without any luck.
[https://github.com/Debitosphere/CNC.TA.Crucial.Scripts/raw/4d023eb45d2c47c43453153488e39fd732a7dd39/CNC.TA.Crucial.Pack.All.in.One.by.Debitosphere.user.js](url)
that is the previous update... try that.
Deb

**Comment by Debitosphere** [comment]
if you are still having issues u can find me on teamspeak server: **allyourbasesbelong2us.com**
so we can attempt to debug your issues.

**Comment by CyBork2000** [comment]
great, so we do it :-)

**Comment by CyBork2000** [comment]
so, i tried now a google chrom portable version with the given older version.
this works fine.
After that, i installed a second google portable version and installed the new one. 
and this works too.
so. the issue can only be my installed chrom version.
sometimes a crosstest befor should be better, but i had no access to the older version befor. so i thought it has to be the new version.
:-) thank you very much for your help.

by the way. is there a chance, to export/ import the login profiles ?
cause i lost it now a second time, and some logins i did not note. 
a stupis work to search them all again ^^

many regards.

**Comment by Debitosphere** [comment]
i did create an exporter for the multilogin but for test purposes only. 3 years ago there was a security issue with making an exporter so a public version was pulled. But I may be able to make a secure version.

**Comment by CyBork2000** [comment]
that would be nice.

And by the way again. This ist the best working and the best usefull script collection i ve ever used/seen.
And your support was very fast Thank you
