### ISSUE TITLE
I can't close or open anything. My cursor will move around but anything I click on, Nothing....

### ISSUE THREAD

**Issue by ldrummer5150** [Debitosphere/CNC.TA.Crucial.Scripts#2]

**Comment by Debitosphere** [comment]
The script update was tested by several players before it was made public.

please try the following....
1. remove the script from tampermonkey and then install it again. The script is a huge file now so it may have been a corrupt download.

2. Clear your browser cache

3. make sure chrome is up to date.

please let me know if one of these methods worked.
