### ISSUE TITLE
Description typo

### ISSUE THREAD

**Issue by Venom564** [Debitosphere/CNC.TA.Crucial.Scripts#3]
Hey Dev

Just wanted to let you know this script ROCKS!!!!!!!!!
now in the db.a.upgrade area under options all
the descriptions of what each icon says the same thing.
heres a video.
https://app.hyfy.io/v/ab0VfDPiLx/

**Comment by Debitosphere** [comment]
I've been meaning to get around to that issue...thx for remindind me.... it will be on the next update.

**Comment by Venom564** [comment]
Since you are a busy man and I was bored I did it for you. Section is from lines 20845 to 20928

							CommandBuildingChoice = new qx.ui.form.Button("Res Only?", null).set({
								toolTipText: "Allows only Resources to upgrade, press 1 for only resources, press 0 for normal procedure, then press the upgrade button",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							worldResBuildingChoice = new qx.ui.form.Button("World", null).set({
								toolTipText: "not pressed looks at everything as it is, New = harvester hungry, Old = Power Plant hungry. However, both options upgrade refineries.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							PowerBuildingChoice = new qx.ui.form.Button("PP's", null).set({
								toolTipText: "P = 0 Stops Power Plants from upgrading, P = 1 Allows Powers Plants to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							HarvBuildingChoice = new qx.ui.form.Button("TibHar", null).set({
								toolTipText: "P = 0 stops Tiberium Harvesters from upgrading, P = 1 allows Tiberium Harvesters to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							
							Harv1BuildingChoice = new qx.ui.form.Button("CryHar", null).set({
								toolTipText: "P = 0 Stops Crystal Harvesters from upgrading, P = 1 Allows Crystal Harvesters to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							
							RefBuildingChoice = new qx.ui.form.Button("Ref's", null).set({
								toolTipText: "P = 0 Stops Refineries from upgrading, P = 1 Allows Refineries to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							
							SiloBuildingChoice = new qx.ui.form.Button("Silo's", null).set({
								toolTipText: "P = 0 Stops Silo's from upgrading, P = 1 Allows Silo's to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});
							
							AccBuildingChoice = new qx.ui.form.Button("Acc's", null).set({
								toolTipText: "P = 0 Stops Accumulators from upgrading, P = 1 Allows Accumulators to upgrade.",
								width: 63,
								height: 30,
								maxWidth: 60,
								maxHeight: 30,
								appearance: ("button-text-small"), //"button-standard-"+factionText), button-playarea-mode-red-frame
								center: true,
								
							});

**Comment by Venom564** [comment]
is there a script that will auto close a defeat or victory tab when one opens? I noticed that if you leave the pc unattended and hit hit all the scripts halt because of a defeat or victory report page when you get attacked by the forgotten

**Comment by Debitosphere** [comment]
First issue fixed.
As for the victory window....
I can put that in on a later release for the V2 TABS sim. :)

**Comment by Debitosphere** [comment]
Fixed Flunik Tools Auto Upgrade took
And Created new script to disable/skip victory report after every attack. Haven't tested if it works for forgotten attacks as well... we'll have to wait and see.
