### ISSUE TITLE
After latest EA patch bunch of stuff doesn't work

### ISSUE THREAD

**Issue by Atilla82** [Debitosphere/CNC.TA.Crucial.Scripts#4]
After latest EA patch bunch of stuff doesn't work.  Resources transfer , click on the icon nothing opens and script error.

Maelstrom tools don't work.

**Comment by Debitosphere** [comment]
I won't be releasing a new update until I've bug fixed everything that
needs to be modified and there are a lot of broken scripts now...
 thanks EA

**Comment by Debitosphere** [comment]
https://forums.ea.com/en/commandandconquer/discussion/102726/crucial-all-in-one#latest
